//
// Generated file, do not edit! Created by nedtool 4.6 from inet/applications/mqttapp/mqttMessages/MqttMsgConnack.msg.
//

#ifndef _INET_MQTTMSGCONNACK_M_H_
#define _INET_MQTTMSGCONNACK_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace inet {

/**
 * Class generated from <tt>inet/applications/mqttapp/mqttMessages/MqttMsgConnack.msg:19</tt> by nedtool.
 * <pre>
 * packet MqttMsgConnack
 * {
 *     //base members
 *     // message type
 *     string type;
 *     // duplicate delivery
 *     bool dupFlag;
 *     // quality of service level
 *     int qosLevel;
 *     // retain flag
 *     bool retain;
 *     // message identifier
 *     string messageId;
 * 
 *     // [v3.1.1] session present flag
 *     bool sessionPresent;
 * 
 *     // return code for CONNACK message
 *     int returnCode;
 * 
 * }
 * </pre>
 */
class MqttMsgConnack : public ::cPacket
{
  protected:
    opp_string type_var;
    bool dupFlag_var;
    int qosLevel_var;
    bool retain_var;
    opp_string messageId_var;
    bool sessionPresent_var;
    int returnCode_var;

  private:
    void copy(const MqttMsgConnack& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MqttMsgConnack&);

  public:
    MqttMsgConnack(const char *name=NULL, int kind=0);
    MqttMsgConnack(const MqttMsgConnack& other);
    virtual ~MqttMsgConnack();
    MqttMsgConnack& operator=(const MqttMsgConnack& other);
    virtual MqttMsgConnack *dup() const {return new MqttMsgConnack(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getType() const;
    virtual void setType(const char * type);
    virtual bool getDupFlag() const;
    virtual void setDupFlag(bool dupFlag);
    virtual int getQosLevel() const;
    virtual void setQosLevel(int qosLevel);
    virtual bool getRetain() const;
    virtual void setRetain(bool retain);
    virtual const char * getMessageId() const;
    virtual void setMessageId(const char * messageId);
    virtual bool getSessionPresent() const;
    virtual void setSessionPresent(bool sessionPresent);
    virtual int getReturnCode() const;
    virtual void setReturnCode(int returnCode);
};

inline void doPacking(cCommBuffer *b, MqttMsgConnack& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MqttMsgConnack& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef _INET_MQTTMSGCONNACK_M_H_

