//
// Generated file, do not edit! Created by nedtool 4.6 from inet/applications/mqttapp/mqttMessages/MqttMsgPuback.msg.
//

#ifndef _INET_MQTTMSGPUBACK_M_H_
#define _INET_MQTTMSGPUBACK_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace inet {

// cplusplus {{
        #include "inet/common/INETDefs.h"
// }}

/**
 * Class generated from <tt>inet/applications/mqttapp/mqttMessages/MqttMsgPuback.msg:24</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet MqttMsgPuback
 * {
 *     int qos;
 *     string messageID;
 *     int status;
 * }
 * </pre>
 */
class MqttMsgPuback : public ::cPacket
{
  protected:
    int qos_var;
    opp_string messageID_var;
    int status_var;

  private:
    void copy(const MqttMsgPuback& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MqttMsgPuback&);

  public:
    MqttMsgPuback(const char *name=NULL, int kind=0);
    MqttMsgPuback(const MqttMsgPuback& other);
    virtual ~MqttMsgPuback();
    MqttMsgPuback& operator=(const MqttMsgPuback& other);
    virtual MqttMsgPuback *dup() const {return new MqttMsgPuback(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getQos() const;
    virtual void setQos(int qos);
    virtual const char * getMessageID() const;
    virtual void setMessageID(const char * messageID);
    virtual int getStatus() const;
    virtual void setStatus(int status);
};

inline void doPacking(cCommBuffer *b, MqttMsgPuback& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MqttMsgPuback& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef _INET_MQTTMSGPUBACK_M_H_

