//
// Generated file, do not edit! Created by nedtool 4.6 from inet/applications/mqttapp/mqttMessages/MqttMsgPingRequest.msg.
//

#ifndef _INET_MQTTMSGPINGREQUEST_M_H_
#define _INET_MQTTMSGPINGREQUEST_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace inet {

// cplusplus {{
        #include "inet/common/INETDefs.h"
// }}

/**
 * Class generated from <tt>inet/applications/mqttapp/mqttMessages/MqttMsgPingRequest.msg:24</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet MqttMsgPingRequest
 * {
 *     int qos;
 *     string messageID;
 *     string clientId;
 *     int bytes;
 * }
 * </pre>
 */
class MqttMsgPingRequest : public ::cPacket
{
  protected:
    int qos_var;
    opp_string messageID_var;
    opp_string clientId_var;
    int bytes_var;

  private:
    void copy(const MqttMsgPingRequest& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MqttMsgPingRequest&);

  public:
    MqttMsgPingRequest(const char *name=NULL, int kind=0);
    MqttMsgPingRequest(const MqttMsgPingRequest& other);
    virtual ~MqttMsgPingRequest();
    MqttMsgPingRequest& operator=(const MqttMsgPingRequest& other);
    virtual MqttMsgPingRequest *dup() const {return new MqttMsgPingRequest(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getQos() const;
    virtual void setQos(int qos);
    virtual const char * getMessageID() const;
    virtual void setMessageID(const char * messageID);
    virtual const char * getClientId() const;
    virtual void setClientId(const char * clientId);
    virtual int getBytes() const;
    virtual void setBytes(int bytes);
};

inline void doPacking(cCommBuffer *b, MqttMsgPingRequest& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MqttMsgPingRequest& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef _INET_MQTTMSGPINGREQUEST_M_H_

