//
// Generated file, do not edit! Created by nedtool 4.6 from inet/applications/mqttapp/mqttMessages/MqttMsgPingResponse.msg.
//

#ifndef _INET_MQTTMSGPINGRESPONSE_M_H_
#define _INET_MQTTMSGPINGRESPONSE_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace inet {

// cplusplus {{
        #include "inet/common/INETDefs.h"
// }}

/**
 * Class generated from <tt>inet/applications/mqttapp/mqttMessages/MqttMsgPingResponse.msg:24</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet MqttMsgPingResponse
 * {
 *     string messageID;
 *     int bytes;
 *     int status;
 * }
 * </pre>
 */
class MqttMsgPingResponse : public ::cPacket
{
  protected:
    opp_string messageID_var;
    int bytes_var;
    int status_var;

  private:
    void copy(const MqttMsgPingResponse& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MqttMsgPingResponse&);

  public:
    MqttMsgPingResponse(const char *name=NULL, int kind=0);
    MqttMsgPingResponse(const MqttMsgPingResponse& other);
    virtual ~MqttMsgPingResponse();
    MqttMsgPingResponse& operator=(const MqttMsgPingResponse& other);
    virtual MqttMsgPingResponse *dup() const {return new MqttMsgPingResponse(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getMessageID() const;
    virtual void setMessageID(const char * messageID);
    virtual int getBytes() const;
    virtual void setBytes(int bytes);
    virtual int getStatus() const;
    virtual void setStatus(int status);
};

inline void doPacking(cCommBuffer *b, MqttMsgPingResponse& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MqttMsgPingResponse& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef _INET_MQTTMSGPINGRESPONSE_M_H_

