//
// Generated file, do not edit! Created by nedtool 4.6 from inet/applications/mqttapp/mqttMessages/MqttMsgSuback.msg.
//

#ifndef _INET_MQTTMSGSUBACK_M_H_
#define _INET_MQTTMSGSUBACK_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace inet {

// cplusplus {{
        #include "inet/common/INETDefs.h"
// }}

/**
 * Class generated from <tt>inet/applications/mqttapp/mqttMessages/MqttMsgSuback.msg:25</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet MqttMsgSuback
 * {
 *     int grantedQosLevels;
 * 
 * }
 * </pre>
 */
class MqttMsgSuback : public ::cPacket
{
  protected:
    int grantedQosLevels_var;

  private:
    void copy(const MqttMsgSuback& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MqttMsgSuback&);

  public:
    MqttMsgSuback(const char *name=NULL, int kind=0);
    MqttMsgSuback(const MqttMsgSuback& other);
    virtual ~MqttMsgSuback();
    MqttMsgSuback& operator=(const MqttMsgSuback& other);
    virtual MqttMsgSuback *dup() const {return new MqttMsgSuback(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getGrantedQosLevels() const;
    virtual void setGrantedQosLevels(int grantedQosLevels);
};

inline void doPacking(cCommBuffer *b, MqttMsgSuback& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MqttMsgSuback& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef _INET_MQTTMSGSUBACK_M_H_

